### ISSUE TITLE
Incorrect IDs and datetime attributes

### ISSUE THREAD

**Issue by acabal** [standardebooks/samuel-pepys_the-diary#5]
@robinwhittleton I was correcting some lint errors in chapter 19 when I noticed that the article IDs appeared to be misdated, and the datetime attributes on  the `<time>` elements were also misdated. I corrected chapter 19 but when looking at chapter 18 I noticed the same problem. For example chapter 18 line 92, the article id is `entry-1661-7-8` and the datetime attribute is `1661-07-08` but the entry appears to be for June 28, not July 8. Am I missing something or is this incorrect?

If this is an issue, note that anchors in endnotes may also have to be fixed. This might get complicated!

**Comment by robinwhittleton** [comment]
This is Gregorian vs Julian dating as far as I can remember. I added some production notes about it:

>• Each diary entry has a time element to start. The datetime attribute is ISO8601 compliant (Gregorian), but the actual dates Pepys uses are Julian, so they don’t appear to match. This is correct.
• This date is copied into the `entry-x` id attribute for each diary entry. Unfortunately, this causes linting to fail with leading 0 errors, so we remove those for the id.

**Comment by acabal** [comment]
Aha, I figured something was up. Should have read the production notes first! I'll undo the "fix" commit.

**Comment by robinwhittleton** [comment]
No problem. It foxed me at the time; istr I wrote a script to generate the dates from the originals?
