### ISSUE TITLE
Duplicate ID attributes

### ISSUE THREAD

**Issue by acabal** [standardebooks/samuel-pepys_the-diary#6]
If you get the latest head of the toolset and run lint on Pepys, it shows that there are a few duplicate ID attributes. They appear to be from different months so they should in fact be different. Usually I'd fix this myself but I don't want to mess with the Gregorian/Julian issues here :)

**Comment by robinwhittleton** [comment]
Fixed in https://github.com/standardebooks/samuel-pepys_the-diary/commit/9dc4fe08aa00e4f624a6abbc050bbc9d0ca4140b.

**Comment by acabal** [comment]
Thanks!
